opt_in_rules:
    - indentation_width
    - operator_usage_whitespace

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - R.generated.swift
  - .build # Where Swift Package Manager checks out dependency sources
  - BuildTools
  
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
- explicit_self

line_length: 
  ignores_comments: true
  
disabled_rules:
  - trailing_comma
